# Generated by Django 5.0.1 on 2025-11-28 02:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='users_email_idx')],
            },
        ),
        migrations.CreateModel(
            name='WordleWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_date', models.DateField(db_index=True, unique=True)),
                ('wordle_number', models.IntegerField(db_index=True, unique=True)),
                ('word', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'wordle_words',
                'ordering': ['-game_date'],
                'indexes': [models.Index(fields=['game_date'], name='wordle_words_date_idx'), models.Index(fields=['wordle_number'], name='wordle_words_num_idx')],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guesses', models.IntegerField(help_text='1-6 for successful solve, 7 for DNF', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.user')),
                ('wordle_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.wordleword')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
        migrations.CreateModel(
            name='UserStatsCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.TextField(choices=[('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly'), ('all_time', 'All Time')])),
                ('period_year', models.IntegerField(blank=True, help_text='NULL for all_time stats', null=True)),
                ('period_value', models.IntegerField(blank=True, help_text='Week (1-53) or Month (1-12), NULL for yearly/all_time', null=True)),
                ('games_played', models.IntegerField(default=0)),
                ('games_solved', models.IntegerField(default=0)),
                ('games_failed', models.IntegerField(default=0)),
                ('total_guesses', models.IntegerField(default=0, help_text='Sum of all guesses for average calculation')),
                ('average_guesses', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('best_score', models.IntegerField(blank=True, help_text='Lowest guess count in period', null=True)),
                ('distribution', models.JSONField(default=dict, help_text='JSON object with guess counts')),
                ('is_winner', models.BooleanField(default=False, help_text='Won this period against other users')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_cache', to='core.user')),
            ],
            options={
                'db_table': 'user_stats_cache',
                'indexes': [models.Index(fields=['user'], name='stats_cache_user_idx'), models.Index(fields=['period_type'], name='stats_cache_type_idx'), models.Index(fields=['last_updated'], name='stats_cache_updated_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userstatscache',
            constraint=models.UniqueConstraint(fields=('user', 'period_type', 'period_year', 'period_value'), name='unique_user_period'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user'], name='scores_user_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['wordle_word'], name='scores_puzzle_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['guesses'], name='scores_guesses_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('user', 'wordle_word'), name='unique_user_puzzle'),
        ),
    ]
